// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57TVETGqWcY2nj5hTpv2dbemB5HK7aJk',
    appId: '1:104526904201:web:1c973da726f77efcc33f58',
    messagingSenderId: '104526904201',
    projectId: 'loginn-2bf15',
    authDomain: 'loginn-2bf15.firebaseapp.com',
    storageBucket: 'loginn-2bf15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdo6P_NjZ_JlcKzMGyx3DPbcSL2VJ2h7s',
    appId: '1:104526904201:android:e4542990c267459ac33f58',
    messagingSenderId: '104526904201',
    projectId: 'loginn-2bf15',
    storageBucket: 'loginn-2bf15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhpUgoT_O09saM1_ejnclIM5abwftG1mA',
    appId: '1:104526904201:ios:0b96e647e85414d2c33f58',
    messagingSenderId: '104526904201',
    projectId: 'loginn-2bf15',
    storageBucket: 'loginn-2bf15.appspot.com',
    iosClientId: '104526904201-7tgqdfh6t4k1qshrrirp960iijoqel1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.gudang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhpUgoT_O09saM1_ejnclIM5abwftG1mA',
    appId: '1:104526904201:ios:8fc2ecc62f2e3596c33f58',
    messagingSenderId: '104526904201',
    projectId: 'loginn-2bf15',
    storageBucket: 'loginn-2bf15.appspot.com',
    iosClientId: '104526904201-qnfhidot8vl9tsude2pr7i9b7nt9l151.apps.googleusercontent.com',
    iosBundleId: 'com.example.gudang.RunnerTests',
  );
}
